### ISSUE TITLE
react version dependency

### ISSUE THREAD

**Issue by bartonmcguire** [re5et/jsxon#1]
It would be rad if `bower.js` didn't depend on a specific version of react (currently ~0.12.2 is specified). My app requires react 0.13.1, which should be plenty compatible with jsxon, but I'm getting dependency conflicts when I bower install

**Comment by re5et** [comment]
This should fix that: https://github.com/re5et/jsxon/commit/c953feda998c6732a6ccca27f570db228162d1c5

Update your dependency for jsxon to 0.0.11
